environment:
  global:
    CHANS_DEV: "-c pyviz/label/dev"
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "doit env_create --name=colorcet --python=%PY%"
  - "activate colorcet"
  - "doit develop_install %CHANS_DEV% -o examples"
  - "doit env_capture"

build: off

test_script:
  - "doit test_all"
